"""
Entry point for the Newsgroups Semantic Search API.

START THE SERVER:
  uvicorn main:app --reload --host 0.0.0.0 --port 8000

FIRST TIME SETUP (run in order):
  1. pip install -r requirements.txt
  2. python -m src.embeddings    ← builds vector store (~5-10 min)
  3. python -m src.clustering    ← runs fuzzy clustering (~5 min)
  4. uvicorn main:app --reload   ← starts the API

API DOCS (auto-generated by FastAPI):
  http://localhost:8000/docs     ← Swagger UI, interactive
  http://localhost:8000/redoc    ← ReDoc, readable
"""

import logging
import uvicorn
from src.api import app  # noqa: F401 — imported for uvicorn to find

# Configure logging format
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)

if __name__ == "__main__":
    # This allows: python main.py (alternative to uvicorn CLI)
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,   # auto-reload on code changes (dev mode)
        log_level="info",
    )
